import { type NextPage } from "next";
import Head from "next/head";
import ClientDetails from "../components/ClientDetails";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container  min-h-screen ">
        <ClientDetails />
      </main>
    </>
  );
};

export default Home;
